### ISSUE TITLE
Build lokal server with sfss endpoint

### ISSUE THREAD

**Issue by FedericoElles** [CoderSyndicate/AppCase#1]
Files to be served
- index.html
- editor.html
- tmpl folder
- res folder

Add sfss: https://github.com/luscus/sfss.api.endpoint
Folder for sfss endpoint: /sfss
API endpoint:  /api/sfss/

Once ready, Fritz will connect the Endpoint with the Editor and we can start editing our portfolio.

**Comment by luscus** [comment]
done.

/sfss => data endpoint
/\*      => static files
